// <auto-generated />
using System;
using CodeMeet.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeMeet.DAL.Migrations
{
    [DbContext(typeof(CodeMeetDbContext))]
    partial class CodeMeetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubjectType")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrgId", "CreatedUtc");

                    b.HasIndex("SessionId", "CreatedUtc");

                    b.HasIndex("UserId", "CreatedUtc");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("SessionId", "CreatedUtc");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("CodeMeet.DAL.QueryModels.SessionSummary", b =>
                {
                    b.Property<double?>("AvgScoreComm")
                        .HasColumnType("double precision");

                    b.Property<double?>("AvgScoreOverall")
                        .HasColumnType("double precision");

                    b.Property<double?>("AvgScoreTech")
                        .HasColumnType("double precision");

                    b.Property<int>("CandidateCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcernsSummary")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExecRequestCount")
                        .HasColumnType("integer");

                    b.Property<int>("InterviewerCount")
                        .HasColumnType("integer");

                    b.Property<int>("ObserverCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrgName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuestionsJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ScheduledEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ScheduledStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("SnippetCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StrengthsSummary")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("ExecRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SnippetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasDefaultValue("Queued");

                    b.Property<string>("Stderr")
                        .HasColumnType("text");

                    b.Property<string>("Stdout")
                        .HasColumnType("text");

                    b.Property<bool>("Truncated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("SnippetId");

                    b.HasIndex("SessionId", "CreatedUtc");

                    b.HasIndex("SessionId", "Status");

                    b.ToTable("exec_requests", (string)null);
                });

            modelBuilder.Entity("Export", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlobUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("OrgId", "CreatedUtc");

                    b.HasIndex("SessionId", "CreatedUtc");

                    b.ToTable("exports", (string)null);
                });

            modelBuilder.Entity("Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CandidateParticipantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Concerns")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ReviewerUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ScoreComm")
                        .HasColumnType("decimal(3,1)");

                    b.Property<decimal?>("ScoreOverall")
                        .HasColumnType("decimal(3,1)");

                    b.Property<decimal?>("ScoreTech")
                        .HasColumnType("decimal(3,1)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Strengths")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CandidateParticipantId");

                    b.HasIndex("ReviewerUserId");

                    b.HasIndex("SessionId", "CreatedUtc");

                    b.ToTable("feedback", (string)null);
                });

            modelBuilder.Entity("Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AcceptedUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("SentUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedUserId");

                    b.HasIndex("SessionId", "Email")
                        .IsUnique();

                    b.ToTable("invitations", (string)null);
                });

            modelBuilder.Entity("Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DataRetentionDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(365);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("OrganizationUser", b =>
                {
                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("OrgId", "UserId");

                    b.HasIndex("UserId");

                    b.HasIndex("OrgId", "Role");

                    b.ToTable("organization_users", (string)null);
                });

            modelBuilder.Entity("Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTime?>("InvitedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsGuest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("JoinedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LeftUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("UserId");

                    b.HasIndex("SessionId", "CreatedUtc");

                    b.HasIndex("SessionId", "Role");

                    b.ToTable("participants", (string)null);
                });

            modelBuilder.Entity("Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("OrgId", "CreatedUtc");

                    b.HasIndex("OrgId", "Level");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("QuestionTag", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("QuestionId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("question_tags", (string)null);
                });

            modelBuilder.Entity("Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasDefaultValue("CSharp");

                    b.Property<bool>("IsExecEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecordingBlobUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ScheduledEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ScheduledStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasDefaultValue("Draft");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ScheduledStartUtc");

                    b.HasIndex("OrgId", "Status");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("SessionQuestion", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("SessionId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SessionId", "OrderIndex");

                    b.ToTable("session_questions", (string)null);
                });

            modelBuilder.Entity("Snippet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Filename")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsFinalSolution")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasDefaultValue("CSharp");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("SessionId", "CreatedUtc");

                    b.HasIndex("SessionId", "IsFinalSolution");

                    b.ToTable("snippets", (string)null);
                });

            modelBuilder.Entity("SnippetComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LineEnd")
                        .HasColumnType("integer");

                    b.Property<int?>("LineStart")
                        .HasColumnType("integer");

                    b.Property<Guid>("SnippetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("SnippetId", "CreatedUtc");

                    b.ToTable("snippet_comments", (string)null);
                });

            modelBuilder.Entity("Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrgId", "Name")
                        .IsUnique();

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("PasswordCreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AuditLog", b =>
                {
                    b.HasOne("Organization", "Org")
                        .WithMany("AuditLogs")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Session", "Session")
                        .WithMany("AuditLogs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Org");

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChatMessage", b =>
                {
                    b.HasOne("User", "AuthorUser")
                        .WithMany("ChatMessages")
                        .HasForeignKey("AuthorUserId");

                    b.HasOne("Session", "Session")
                        .WithMany("ChatMessages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorUser");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ExecRequest", b =>
                {
                    b.HasOne("User", "RequestedByUser")
                        .WithMany("ExecRequests")
                        .HasForeignKey("RequestedByUserId");

                    b.HasOne("Session", "Session")
                        .WithMany("ExecRequests")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Snippet", "Snippet")
                        .WithMany("ExecRequests")
                        .HasForeignKey("SnippetId");

                    b.Navigation("RequestedByUser");

                    b.Navigation("Session");

                    b.Navigation("Snippet");
                });

            modelBuilder.Entity("Export", b =>
                {
                    b.HasOne("User", "CreatedByUser")
                        .WithMany("Exports")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Organization", "Org")
                        .WithMany("Exports")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Session", "Session")
                        .WithMany("Exports")
                        .HasForeignKey("SessionId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Org");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Feedback", b =>
                {
                    b.HasOne("Participant", "CandidateParticipant")
                        .WithMany("FeedbacksAsCandidate")
                        .HasForeignKey("CandidateParticipantId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("User", "ReviewerUser")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ReviewerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Session", "Session")
                        .WithMany("Feedbacks")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateParticipant");

                    b.Navigation("ReviewerUser");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Invitation", b =>
                {
                    b.HasOne("User", "AcceptedUser")
                        .WithMany("AcceptedInvitations")
                        .HasForeignKey("AcceptedUserId");

                    b.HasOne("Session", "Session")
                        .WithMany("Invitations")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcceptedUser");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("OrganizationUser", b =>
                {
                    b.HasOne("Organization", "Org")
                        .WithMany("Members")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany("OrganizationMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Org");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Participant", b =>
                {
                    b.HasOne("Session", "Session")
                        .WithMany("Participants")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany("Participants")
                        .HasForeignKey("UserId");

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Question", b =>
                {
                    b.HasOne("User", "CreatedByUser")
                        .WithMany("Questions")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Organization", "Org")
                        .WithMany("Questions")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Org");
                });

            modelBuilder.Entity("QuestionTag", b =>
                {
                    b.HasOne("Question", "Question")
                        .WithMany("QuestionTags")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tag", "Tag")
                        .WithMany("QuestionTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Session", b =>
                {
                    b.HasOne("User", "CreatedByUser")
                        .WithMany("CreatedSessions")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Organization", "Org")
                        .WithMany("Sessions")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Org");
                });

            modelBuilder.Entity("SessionQuestion", b =>
                {
                    b.HasOne("Question", "Question")
                        .WithMany("SessionQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Session", "Session")
                        .WithMany("SessionQuestions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Snippet", b =>
                {
                    b.HasOne("User", "AuthorUser")
                        .WithMany("Snippets")
                        .HasForeignKey("AuthorUserId");

                    b.HasOne("Session", "Session")
                        .WithMany("Snippets")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorUser");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SnippetComment", b =>
                {
                    b.HasOne("User", "AuthorUser")
                        .WithMany("SnippetComments")
                        .HasForeignKey("AuthorUserId");

                    b.HasOne("Snippet", "Snippet")
                        .WithMany("Comments")
                        .HasForeignKey("SnippetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorUser");

                    b.Navigation("Snippet");
                });

            modelBuilder.Entity("Tag", b =>
                {
                    b.HasOne("Organization", "Org")
                        .WithMany("Tags")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Org");
                });

            modelBuilder.Entity("Organization", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Exports");

                    b.Navigation("Members");

                    b.Navigation("Questions");

                    b.Navigation("Sessions");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Participant", b =>
                {
                    b.Navigation("FeedbacksAsCandidate");
                });

            modelBuilder.Entity("Question", b =>
                {
                    b.Navigation("QuestionTags");

                    b.Navigation("SessionQuestions");
                });

            modelBuilder.Entity("Session", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("ChatMessages");

                    b.Navigation("ExecRequests");

                    b.Navigation("Exports");

                    b.Navigation("Feedbacks");

                    b.Navigation("Invitations");

                    b.Navigation("Participants");

                    b.Navigation("SessionQuestions");

                    b.Navigation("Snippets");
                });

            modelBuilder.Entity("Snippet", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ExecRequests");
                });

            modelBuilder.Entity("Tag", b =>
                {
                    b.Navigation("QuestionTags");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("AcceptedInvitations");

                    b.Navigation("AuditLogs");

                    b.Navigation("ChatMessages");

                    b.Navigation("CreatedSessions");

                    b.Navigation("ExecRequests");

                    b.Navigation("Exports");

                    b.Navigation("Feedbacks");

                    b.Navigation("OrganizationMemberships");

                    b.Navigation("Participants");

                    b.Navigation("Questions");

                    b.Navigation("SnippetComments");

                    b.Navigation("Snippets");
                });
#pragma warning restore 612, 618
        }
    }
}
